version: '3.8'

services:
  landing:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/usr/src/app
    restart: always  # Automatically restart the container if it stops
    networks:
      - landing-network

networks:
  landing-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
